### ISSUE TITLE
Write documentation for source importing

### ISSUE THREAD

**Issue by bretelerjmw** [discipl/flinteditor-mps#199]
```
label:documentation
label:ready
assigned:daron
```

## Introduction

Importing sources is an essential feature of the editor.

It is also a complex feature that has seen several reworks.

The feature is also expected to be reworked in future to support Linked Data imports.

For these reasons, it is helpful to document it.

## Task breakdown

- [ ] Write brief dev documentation about the process of source importing
    - Mention which parts of the codebase are involved
    - Where helpful, feel free to refer to general MPS documentation
- [ ] Add code comments for the more complex parts of the code
- [ ] Schedule a meeting with Jeroen to review

**Comment by blackstardlb** [comment]
example diagram
![source-importing](https://user-images.githubusercontent.com/15971736/179979596-adf6444a-e78b-4a20-a1ee-89b14fa3e0e3.png)

**Comment by blackstardlb** [comment]
Include abstract component-diagram
